url: https://worldmodels-rlc.github.io
baseurl:

# Site settings
title: RLC-WMW Workshop
email: worldmodelworkshop@gmail.com
description: "Workshop on Model-Based Reinforcement Learning and Generative World Models @ RLC 2026"

# Organizers (shown in Team section)
people:
- name: Mohamad H. Danesh
  pic: mohamad_danesh
  affiliation: McGill University & Mila
  role: Lead Organizer
  homepage: https://modanesh.github.io

- name: Amin Abyaneh
  pic: amin_abyaneh
  affiliation: McGill University & Mila
  role: Co-organizer
  homepage: https://aminabyaneh.github.io

- name: Michael Przystupa
  pic: michael_sunshine
  pic_ext: jpeg
  affiliation: Vrije Universiteit Amsterdam
  role: Co-organizer
  homepage: https://mi-przystupa.github.io/

- name: Chenhao Li
  pic: chenhao_li
  pic_ext: png
  affiliation: ETH Zurich
  role: Co-organizer
  homepage: https://breadli428.github.io/

- name: Huihan Liu
  pic: huihan_liu
  pic_ext: png
  affiliation: UT Austin
  role: Co-organizer
  homepage: https://huihanl.github.io/

- name: Glen Berseth
  pic: glen_berseth
  pic_ext: png
  affiliation: Mila & UdeM
  role: Senior Advisor
  homepage: https://neo-x.github.io

- name: Stan Birchfield
  pic: stan_birchfield
  affiliation: Nvidia
  role: Industry Advisor
  homepage: https://cecas.clemson.edu/~stb/

- name: Hsiu-Chin Lin
  pic: hsiuchin_lin
  affiliation: McGill University & Mila
  role: Senior Advisor
  homepage: https://sites.google.com/site/hsiuchinlin/

# Social links
social:
  - title: github
    url: https://github.com/worldmodels-rlc

# Workshop address / venue
address:
  - line: "RLC 2026"
  - line: "August 15, 2026"

# Build settings
markdown: kramdown
permalink: pretty
